name: Serenity Selenium Bootstrap CI/CD

on:
  push:
    branches:
      - main
      - "feature/*"
  pull_request:
    branches: 
      - main

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Build Gradle and SonarCloud Scan
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: gradle sonarqube -Dsonar.host.url=https://sonarcloud.io -Dsonar.projectKey=serenity-selenium-bootstrap --warning-mode=all
    - name: Test execution
      uses: gradle/gradle-build-action@v2.0.1
      with:
        arguments: -DBASE_URL=${{ secrets.BASE_URL }} -DADMIN_USER=${{ secrets.ADMIN_USER }} -DADMIN_PASSWORD=${{ secrets.ADMIN_PASSWORD }} clean test aggregate
    - name: Publish test report
      if: always()
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        BRANCH: serenity-report-execution
        FOLDER: ./target/site/serenity
        CLEAN: true
