name: Serenity-Selenium-Bootstrap CI/CD

on:
  push:
    branches:
      - main
      - "feature/*"
  pull_request:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2.0.1
        with:
         arguments: clean build -x test
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: ./src
          args: >
            -Dsonar.projectKey=serenity-selenium-bootstrap
            -Dsonar.sources=main/java
            -Dsonar.tests=test/java
            -Dsonar.java.binaries=/github/workspace/build/classes
            -Dsonar.java.libraries=/github/workspace/build/libs
      - name: Test execution
        uses: gradle/gradle-build-action@v2.0.1
        with:
          arguments: -DBASE_URL=${{ secrets.BASE_URL }} -DREGISTERED_USER=${{ secrets.REGISTERED_USER }} -DREGISTERED_PASSWORD=${{ secrets.REGISTERED_PASSWORD }} clean test aggregate

        
