name: Screenplay-java-Bootstrap CI/CD

on:
  push:
    branches:
      - main
      - "feature/*"
  pull_request:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: "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"
          SONAR_HOST_URL: "347c8f3ab5931343897ba8132731bbe814e71942"
        with:
          projectBaseDir: ./src
          args: >
            -Dsonar.projectKey=serenity-selenium-bootstrap
            -Dsonar.sources=main/java
            -Dsonar.tests=test/java
            -Dsonar.java.binaries=/github/workspace/build/classes
            -Dsonar.java.libraries=/github/workspace/build/libs
        
