name: Serenity-Selenium-Bootstrap CI/CD

on:
  push:
    branches:
      - main
      - "feature/*"
  pull_request:
    branches:
      - main
jobs:
  # This workflow contains a single job called "greet"
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        java-version: 1.8
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
         arguments: clean build
